apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobileshop
  name: mobileshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobileshop
  template:
    metadata:
      labels:
        app: mobileshop
    spec:
      containers:
      - image: ahk3983/mobileshop:latest
        name: vote
        ports:
        - containerPort: 80
          name: mobileshop
